update cli docs
helium/router pull request #543
Opened 2021-12-08 00:18 UTC by michaeldjeffrey

More documentation for https://github.com/helium/router/issues/522 and https://github.com/helium/router/issues/427

2021-12-08 00:49 UTC, dpezely requested changes
Mostly minor wording nitpicks, plus one spot where wording wasn't clear on first reading.

2021-12-08 00:49 UTC, dpezely commented on docs/Device.md
> +### Tracing
Is tracing part of the info command?  If a separate command, there's no usage/example.  If part of the info command as implied by `--stop` mentioned below, it's confusing being within a separate subsection.

2021-12-08 00:49 UTC, dpezely commented on docs/Organizations.md
> +Similar to Devices, Console is the source of truth for Organizations DC balance.
Keeping consistent with usage farther below:

```suggestion
Similar to Devices, Console is the source of truth for an organization's DC balance.
```

2021-12-08 00:49 UTC, dpezely commented on docs/Organizations.md
> +A way to update an organizations DC balance in Console from Router.
```suggestion
A way to update an organization's DC balance in Console from Router.
```

2021-12-08 00:49 UTC, dpezely commented on docs/Device.md
> +Router maintains a databse in Rocks of Devices, but the paired Console instance should always be viewed as the source of truth for a Device.
```suggestion
Router maintains a database in RocksDB of Devices, but the paired Console instance should always be viewed as the source of truth for a Device.
```

2021-12-10 16:19 UTC, dpezely submitted a review, later dismissed

2021-12-13 19:45 UTC, macpie approved these changes

2021-12-13 19:45 UTC, merged