fix xor filter reporting error when not all filters are in use
helium/router pull request #693
Opened 2022-04-11 23:32 UTC by michaeldjeffrey

2022-04-11 23:50 UTC, dpezely requested changes
Please add a comment explaining the rationale behind the logic; 
e.g.,  more than just the fact that these lists need to be of a particular length-- but why that's significant.

2022-04-12 18:33 UTC, michaeldjeffrey commented
> Please add a comment explaining the rationale behind the logic; e.g., more than just the fact that these lists need to be of a particular length-- but why that's significant.

I thought about this for a bit, and ended up moving the sizing to the cli module.
For the XOR filter worker, the size of the list is not significant.

2022-04-12 18:58 UTC, dpezely approved these changes

2022-04-13 16:22 UTC, macpie approved these changes

2022-04-13 16:22 UTC, merged